### PR TITLE
Register shell properly for newer versions of Starship

### LINKED ISSUE #4: Set `$STARSHIP_SHELL = "xonsh"` instead of "sh"
Xonsh is supported natively in starship now (see `/usr/local/bin/starship init xonsh --print-full-init`), and each supported shell sets the `$STARSHIP_SHELL` variable to the running shell. This project just defaults that variable to "sh", which is not ideal. It means that adding custom sections to the starship.toml file for different shells can't simply check this variable is "xonsh" as a conditional.

This issue is a proposal to change this line to use 'xonsh' instead of 'sh': https://github.com/anki-code/xontrib-prompt-starship/blob/cd031590c9c0a78c919b02dadc15ce093046ee45/xontrib/prompt_starship.py#L5

### PR DESCRIPTION
**Pull request by ofek**
Resolves #4

### CODE REVIEW

**Comment by anki-code** [comment]
Thanks @ofek !

**Comment by ofek** [comment]
Thank you! Will this be released soon?

**Comment by anki-code** [comment]
Released!

**Comment by ofek** [comment]
Thanks!!!

**Pull request merged**
